version: '3.8'

services:
  # Для сборки
  nodejs:
    build:
      context: .
      dockerfile: ./docker/nodejs/Dockerfile
    tty: true
    ports:
      - "5173:5173"
    working_dir: /var/www
    volumes:
      - .:/var/www # Монтируем локальную папку в контейнер как /var/www