version: '3.6'

services:
    backend:
        image: nginx
        hostname: project2
        ports:
            - "8082:80"
        networks:
            some_network:
                aliases:
                    - project2.local
                    - www.project2.local

networks:
    some_network:
        # Общая сеть со смежными проектами
        name: 'our_network'